name: crypto_flutter_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  cached_network_image: 3.0.0
  either_dart: ^0.1.4
  json_annotation: ^4.3.0
  syncfusion_flutter_charts: ^19.1.67
  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  json_serializable: ^6.1.3
  provider: ^6.0.3
  shared_preferences: ^2.0.11
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

